# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af7099931afd7a49b9bf84e79030e74f"
name = "cart validation"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "psurya.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
